/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author RAHUL
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        panelPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        idusuarioaminnis = new javax.swing.JTextField();
        lblusuario = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        registros = new javax.swing.JMenu();
        itemmiembros = new javax.swing.JMenuItem();
        itemlideriglesia = new javax.swing.JMenuItem();
        itemministerio = new javax.swing.JMenuItem();
        itemregistrardiezmo = new javax.swing.JMenuItem();
        itemoregistrarfrenda = new javax.swing.JMenuItem();
        itemMembrecia = new javax.swing.JMenu();
        itemLista = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemIglesia = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemDiezmo = new javax.swing.JMenuItem();
        itemOfrenda = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itemRegistro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuev.png"))); // NOI18N

        lblusuario.setEditable(false);

        panelPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelPrincipal.setLayer(idusuarioaminnis, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelPrincipal.setLayer(lblusuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(idusuarioaminnis, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idusuarioaminnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu-button_icon-icons.com_72989 (2).png"))); // NOI18N
        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        jMenuItem7.setText("Acerca de la Iglesia");
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        registros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lightbrown_books_folders_12307 (1).png"))); // NOI18N
        registros.setText("Registros");
        registros.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        itemmiembros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon registro.png"))); // NOI18N
        itemmiembros.setText("Registrar Miembros");
        registros.add(itemmiembros);

        itemlideriglesia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconnew1.png"))); // NOI18N
        itemlideriglesia.setText("Registrar Líder de la iglesia");
        itemlideriglesia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemlideriglesiaActionPerformed(evt);
            }
        });
        registros.add(itemlideriglesia);

        itemministerio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconnew2.png"))); // NOI18N
        itemministerio.setText("Registrar Lider de ministerios");
        registros.add(itemministerio);

        itemregistrardiezmo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconnew3.png"))); // NOI18N
        itemregistrardiezmo.setText("Registrar Diezmos");
        registros.add(itemregistrardiezmo);

        itemoregistrarfrenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconnew4.png"))); // NOI18N
        itemoregistrarfrenda.setText("Registrar Ofrendas");
        itemoregistrarfrenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemoregistrarfrendaActionPerformed(evt);
            }
        });
        registros.add(itemoregistrarfrenda);

        jMenuBar1.add(registros);

        itemMembrecia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libraryfolder_books_binders_2688 (1).png"))); // NOI18N
        itemMembrecia.setText("Membrecia");
        itemMembrecia.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        itemLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconlistama.png"))); // NOI18N
        itemLista.setText("Lista de Miembros");
        itemMembrecia.add(itemLista);

        jMenuBar1.add(itemMembrecia);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconliders.png"))); // NOI18N
        jMenu4.setText("Liderazgo");
        jMenu4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        itemIglesia.setText("Líderes de la Iglesia");
        itemIglesia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIglesiaActionPerformed(evt);
            }
        });
        jMenu4.add(itemIglesia);

        jMenuItem3.setText("Líderes de Ministerio Femenil");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Líderes de Ministerio Juvenil");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Líderes de Ministerio Pre Juvenil");
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Líderes de Ministerio de Alabanza");
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4288584andbusinessfinancepersonalportfolioprofileresume-115772_115741 (1).png"))); // NOI18N
        jMenu3.setText("Finanzas");
        jMenu3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        itemDiezmo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconcalve.png"))); // NOI18N
        itemDiezmo.setText("Diezmo");
        jMenu3.add(itemDiezmo);

        itemOfrenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconcalplo.png"))); // NOI18N
        itemOfrenda.setText("Ofrenda");
        jMenu3.add(itemOfrenda);

        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/users_clients_group_16774.png"))); // NOI18N
        jMenu5.setText("Usuarios");
        jMenu5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N

        itemRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconnewuser.png"))); // NOI18N
        itemRegistro.setText("Registro de Usuarios");
        jMenu5.add(itemRegistro);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void itemlideriglesiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemlideriglesiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemlideriglesiaActionPerformed

    private void itemoregistrarfrendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemoregistrarfrendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemoregistrarfrendaActionPerformed

    private void itemIglesiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIglesiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIglesiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField idusuarioaminnis;
    public javax.swing.JMenuItem itemDiezmo;
    public javax.swing.JMenuItem itemIglesia;
    public javax.swing.JMenuItem itemLista;
    public javax.swing.JMenu itemMembrecia;
    public javax.swing.JMenuItem itemOfrenda;
    public javax.swing.JMenuItem itemRegistro;
    public javax.swing.JMenuItem itemlideriglesia;
    public javax.swing.JMenuItem itemmiembros;
    private javax.swing.JMenuItem itemministerio;
    public javax.swing.JMenuItem itemoregistrarfrenda;
    public javax.swing.JMenuItem itemregistrardiezmo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollBar jScrollBar1;
    public javax.swing.JTextField lblusuario;
    public javax.swing.JDesktopPane panelPrincipal;
    private javax.swing.JMenu registros;
    // End of variables declaration//GEN-END:variables
}
