/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import java.awt.event.KeyEvent;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author RAHUL
 */
public class VistaMembrecia extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaMembrecia
     */
    public VistaMembrecia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtpaterno = new javax.swing.JTextField();
        txtdocumento = new javax.swing.JTextField();
        boxestado = new javax.swing.JComboBox<>();
        datevonversion = new com.toedter.calendar.JDateChooser();
        datebautizo = new com.toedter.calendar.JDateChooser();
        datenacimiento = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablademiembros = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtmaterno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        botonnuevo = new javax.swing.JButton();
        botonagregar = new javax.swing.JButton();
        botoncancelar = new javax.swing.JButton();
        botonmodificar = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        botonreporte = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        botonlistar = new javax.swing.JButton();
        boxactivo = new javax.swing.JComboBox<>();
        boxtalentos = new javax.swing.JComboBox<>();
        boxdones = new javax.swing.JComboBox<>();
        btnbuscar1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        txtnomfererencia = new javax.swing.JTextField();
        txtnumreferencia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setTitle("REGISTRO DE MEMBRECÍA");

        jLabel2.setText("Nombres:");

        jLabel3.setText("Apellido Paterno:");

        jLabel4.setText("N° Documento:");

        jLabel5.setText("Fecha de Nacimiento:");

        jLabel6.setText("Estado civil:");

        jLabel7.setText("Fecha de bautismo:");

        jLabel8.setText("Fecha de conversion:");

        jLabel9.setText("Talentos:");

        jLabel10.setText("Activo:");

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        txtpaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaternoActionPerformed(evt);
            }
        });
        txtpaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpaternoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpaternoKeyTyped(evt);
            }
        });

        txtdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocumentoActionPerformed(evt);
            }
        });
        txtdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdocumentoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdocumentoKeyTyped(evt);
            }
        });

        boxestado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boxestadoKeyPressed(evt);
            }
        });

        datevonversion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                datevonversionKeyPressed(evt);
            }
        });

        datebautizo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                datebautizoKeyPressed(evt);
            }
        });

        datenacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                datenacimientoKeyPressed(evt);
            }
        });

        tablademiembros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "APELLIDO P.", "APELLIDO M.", "C.I.", "FECHA NACIMIENTO", "ESTADO CIVIL", "FECHA CONVERSION", "FECHA BAUTIZO", "TALENTOS", "DONES", "ACTIVO", "DIRECCION", "NOMBRE REFERENCIA", "NUMERO REFERENCIA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablademiembros);

        jLabel12.setText("Apellido Materno:");

        txtmaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaternoActionPerformed(evt);
            }
        });
        txtmaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmaternoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Mayus(evt);
            }
        });

        jLabel11.setText("Dones:");

        botonnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon nuevo.png"))); // NOI18N
        botonnuevo.setText("NUEVO");

        botonagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon registro.png"))); // NOI18N
        botonagregar.setText("REGISTRAR");
        botonagregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonagregarKeyPressed(evt);
            }
        });

        botoncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconcance.png"))); // NOI18N
        botoncancelar.setText("CANCELAR");
        botoncancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botoncancelarKeyPressed(evt);
            }
        });

        botonmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconmodificar.png"))); // NOI18N
        botonmodificar.setText("MODIFICAR");
        botonmodificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonmodificarKeyPressed(evt);
            }
        });

        botoneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconeliminar.png"))); // NOI18N
        botoneliminar.setText("ELIMINAR");
        botoneliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botoneliminarKeyPressed(evt);
            }
        });

        botonreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconexcel.png"))); // NOI18N
        botonreporte.setText("EXPORTAR");
        botonreporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botonreporteKeyPressed(evt);
            }
        });

        txtbuscar.setToolTipText("");
        txtbuscar.setName(""); // NOI18N

        jLabel13.setText("BUSCAR:");

        botonlistar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconlistaboton.png"))); // NOI18N
        botonlistar.setText("RECARGAR");
        botonlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonlistarActionPerformed(evt);
            }
        });

        boxactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxactivoActionPerformed(evt);
            }
        });
        boxactivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boxactivoKeyPressed(evt);
            }
        });

        boxtalentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxtalentosActionPerformed(evt);
            }
        });
        boxtalentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boxtalentosKeyPressed(evt);
            }
        });

        boxdones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIN ESPECIFICAR", "PALABRA DE SABIDURÍA", "PALABRA DE CONOCIMIENTO", "FE", "DONES DE SANIDAD", "PODER DE MILAGROS", "PROFECÍA", "DISCERNIMIENTO DE ESPÍRITUS", "DIVERSAS CLASES DE LENGUAS", "INTERPRETACIÓN DE LENGUAS", "SERVICIO", "ENSEÑANZA", "EXHORTACIÓN", "DAR", "LIDERAZGO", "MISERICORDIA" }));
        boxdones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxdonesActionPerformed(evt);
            }
        });
        boxdones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boxdonesKeyPressed(evt);
            }
        });

        btnbuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconbuscar.png"))); // NOI18N
        btnbuscar1.setText("BUSCAR");
        btnbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Dirección:");

        jLabel15.setText("Nombre de Referencia:");

        jLabel16.setText("Número de Referencia:");

        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });

        txtnomfererencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomfererenciaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomfererenciaKeyTyped(evt);
            }
        });

        txtnumreferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumreferenciaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumreferenciaKeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbuscar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonlistar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxestado, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(datevonversion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxactivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnomfererencia, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnumreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(datebautizo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(boxtalentos, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(boxdones, 0, 1, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(datenacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonnuevo)
                        .addGap(18, 18, 18)
                        .addComponent(botonagregar)
                        .addGap(18, 18, 18)
                        .addComponent(botoncancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonmodificar)
                        .addGap(18, 18, 18)
                        .addComponent(botoneliminar)
                        .addGap(18, 18, 18)
                        .addComponent(botonreporte))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(datenacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(txtpaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(txtmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7)
                                .addComponent(datebautizo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(boxtalentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxdones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9))
                                .addComponent(datevonversion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(boxestado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnomfererencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtnumreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxactivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbuscar1)
                    .addComponent(botonlistar)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonnuevo)
                    .addComponent(botonagregar)
                    .addComponent(botoncancelar)
                    .addComponent(botonmodificar)
                    .addComponent(botoneliminar)
                    .addComponent(botonreporte))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtpaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaternoActionPerformed

    private void txtmaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaternoActionPerformed

    private void boxactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxactivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxactivoActionPerformed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        String nom=txtnombre.getText();
        char validar=evt.getKeyChar();
        if(nom.length()>0){
            char primletra=nom.charAt(0);
            nom=Character.toUpperCase(primletra)+nom.substring(1, nom.length() );
            txtnombre.setText(nom);
        }else if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "INGRESE SOLO LETRAS");
        }
        
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtpaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpaternoKeyTyped
        String nom=txtpaterno.getText();
        char validar=evt.getKeyChar();
        if(nom.length()>0){
            char primletra=nom.charAt(0);
            nom=Character.toUpperCase(primletra)+nom.substring(1, nom.length() );
            txtpaterno.setText(nom);
        }else if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "INGRESE SOLO LETRAS");
        }
    }//GEN-LAST:event_txtpaternoKeyTyped

    private void Mayus(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Mayus
        String nom=txtmaterno.getText();
        char validar=evt.getKeyChar();
        if(nom.length()>0){
            char primletra=nom.charAt(0);
            nom=Character.toUpperCase(primletra)+nom.substring(1, nom.length() );
            txtmaterno.setText(nom);
        }else if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "INGRESE SOLO LETRAS");
        }
    }//GEN-LAST:event_Mayus

    private void boxtalentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxtalentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxtalentosActionPerformed

    private void boxdonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxdonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxdonesActionPerformed

    private void txtdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocumentoActionPerformed
        
    }//GEN-LAST:event_txtdocumentoActionPerformed

    private void txtdocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocumentoKeyTyped
        char validar=evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "INGRESE SOLO NUMEROS");
        }
    }//GEN-LAST:event_txtdocumentoKeyTyped
///////////EVENTOS KEY PRESSED
    private void txtnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyPressed
        if(evt.getExtendedKeyCode() == KeyEvent.VK_RIGHT){
            txtpaterno.requestFocus();
        }
    }//GEN-LAST:event_txtnombreKeyPressed

    private void txtpaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpaternoKeyPressed
        if(evt.getExtendedKeyCode() == KeyEvent.VK_RIGHT){
            txtmaterno.requestFocus();
        }else if(evt.getExtendedKeyCode() == KeyEvent.VK_LEFT){
            txtnombre.requestFocus();
        }
    }//GEN-LAST:event_txtpaternoKeyPressed

    private void txtdocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocumentoKeyPressed
        if(evt.getExtendedKeyCode() == KeyEvent.VK_RIGHT){
            boxestado.requestFocus();
        }else if(evt.getExtendedKeyCode() == KeyEvent.VK_LEFT){
            txtmaterno.requestFocus();
        }
    }//GEN-LAST:event_txtdocumentoKeyPressed

    private void datenacimientoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datenacimientoKeyPressed
        
    }//GEN-LAST:event_datenacimientoKeyPressed

    private void boxestadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxestadoKeyPressed
       if(evt.getExtendedKeyCode() == KeyEvent.VK_RIGHT){
            boxtalentos.requestFocus();
        }else if(evt.getExtendedKeyCode() == KeyEvent.VK_LEFT){
            datenacimiento.requestFocus();
        }
    }//GEN-LAST:event_boxestadoKeyPressed

    private void txtmaternoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmaternoKeyPressed
        if(evt.getExtendedKeyCode() == KeyEvent.VK_RIGHT){
            txtdocumento.requestFocus();
        }else if(evt.getExtendedKeyCode() == KeyEvent.VK_LEFT){
            txtpaterno.requestFocus();
        }
    }//GEN-LAST:event_txtmaternoKeyPressed

    private void datevonversionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datevonversionKeyPressed
        
    }//GEN-LAST:event_datevonversionKeyPressed

    private void datebautizoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datebautizoKeyPressed
        
    }//GEN-LAST:event_datebautizoKeyPressed

    private void boxtalentosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxtalentosKeyPressed
        if(evt.getExtendedKeyCode() == KeyEvent.VK_RIGHT){
            boxdones.requestFocus();
        }else if(evt.getExtendedKeyCode() == KeyEvent.VK_LEFT){
            datebautizo.requestFocus();
        }
    }//GEN-LAST:event_boxtalentosKeyPressed

    private void boxdonesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxdonesKeyPressed
        if(evt.getExtendedKeyCode() == KeyEvent.VK_RIGHT){
            boxactivo.requestFocus();
        }else if(evt.getExtendedKeyCode() == KeyEvent.VK_LEFT){
            boxtalentos.requestFocus();
        }
    }//GEN-LAST:event_boxdonesKeyPressed

    private void boxactivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxactivoKeyPressed
        if(evt.getExtendedKeyCode() == KeyEvent.VK_LEFT){
            botonagregar.requestFocus();
        }else if(evt.getExtendedKeyCode() == KeyEvent.VK_RIGHT){
            boxdones.requestFocus();
        }
    }//GEN-LAST:event_boxactivoKeyPressed

    private void botonagregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonagregarKeyPressed
        if(evt.getExtendedKeyCode() == KeyEvent.VK_RIGHT){
            botoncancelar.requestFocus();
        }else if(evt.getExtendedKeyCode() == KeyEvent.VK_UP){
            txtnumreferencia.requestFocus();
        }
    }//GEN-LAST:event_botonagregarKeyPressed

    private void botoncancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botoncancelarKeyPressed
        switch (evt.getExtendedKeyCode()) {
            case KeyEvent.VK_LEFT:
                botonagregar.requestFocus();
                break;
            case KeyEvent.VK_UP:
                txtnumreferencia.requestFocus();
                break;
            case KeyEvent.VK_RIGHT:
                botonmodificar.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_botoncancelarKeyPressed

    private void botonlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonlistarActionPerformed
        
    }//GEN-LAST:event_botonlistarActionPerformed

    private void btnbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar1ActionPerformed
        // 
    }//GEN-LAST:event_btnbuscar1ActionPerformed

    private void txtdireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyPressed
        if(evt.getExtendedKeyCode() == KeyEvent.VK_RIGHT){
            txtnomfererencia.requestFocus();
        }else if(evt.getExtendedKeyCode() == KeyEvent.VK_LEFT){
            boxactivo.requestFocus();
        }
    }//GEN-LAST:event_txtdireccionKeyPressed

    private void txtnomfererenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomfererenciaKeyPressed
        if(evt.getExtendedKeyCode() == KeyEvent.VK_RIGHT){
            txtnumreferencia.requestFocus();
        }else if(evt.getExtendedKeyCode() == KeyEvent.VK_LEFT){
            txtdireccion.requestFocus();
        }
    }//GEN-LAST:event_txtnomfererenciaKeyPressed

    private void txtnumreferenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumreferenciaKeyPressed
        switch (evt.getExtendedKeyCode()) {
            case KeyEvent.VK_RIGHT:
                botonagregar.requestFocus();
                break;
            case KeyEvent.VK_LEFT:
                txtnomfererencia.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                botonagregar.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_txtnumreferenciaKeyPressed

    private void botonmodificarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonmodificarKeyPressed
        switch (evt.getExtendedKeyCode()) {
            case KeyEvent.VK_RIGHT:
                botoneliminar.requestFocus();
                break;
            case KeyEvent.VK_LEFT:
                botoncancelar.requestFocus();
                break;
            case KeyEvent.VK_UP:
                txtnumreferencia.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_botonmodificarKeyPressed

    private void botoneliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botoneliminarKeyPressed
        switch (evt.getExtendedKeyCode()) {
            case KeyEvent.VK_RIGHT:
                botonreporte.requestFocus();
                break;
            case KeyEvent.VK_LEFT:
                botonmodificar.requestFocus();
                break;
            case KeyEvent.VK_UP:
                txtnumreferencia.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_botoneliminarKeyPressed

    private void botonreporteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonreporteKeyPressed
        switch (evt.getExtendedKeyCode()) {
            case KeyEvent.VK_RIGHT:
                botonagregar.requestFocus();
                break;
            case KeyEvent.VK_LEFT:
                botoneliminar.requestFocus();
                break;
            case KeyEvent.VK_UP:
                txtnumreferencia.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_botonreporteKeyPressed

    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped
        String dir=txtdireccion.getText();
        txtdireccion.setText(capitalizeFirstLetter(dir));
    }//GEN-LAST:event_txtdireccionKeyTyped

    private void txtnomfererenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomfererenciaKeyTyped
        char validar = evt.getKeyChar();
    
        // Bloquear números
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "INGRESE SOLO LETRAS");
            return;
        }

        // Permitir solo letras y espacios
        if (!Character.isLetter(validar) && validar != ' ' && validar != KeyEvent.VK_BACK_SPACE) {
            getToolkit().beep();
            evt.consume();
            return;
        }

        // Obtener el texto actual
        SwingUtilities.invokeLater(() -> {
            String texto = txtpaterno.getText();
            if (!texto.isEmpty()) {
                txtpaterno.setText(capitalizeFirstLetter(texto));
            }
        });
            String nomref=txtnomfererencia.getText();
            txtnomfererencia.setText(capitalizeFirstLetter(nomref));
        
    }//GEN-LAST:event_txtnomfererenciaKeyTyped

    private void txtnumreferenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumreferenciaKeyTyped
            
        //verificarDocumento();
        char validar = evt.getKeyChar();

        // Verificar si ya hay 8 caracteres en el campo de texto
        if (txtnumreferencia.getText().length() >= 8) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "SOLO SE PERMITEN 8 DÍGITOS");
            return; // Salir para evitar más validaciones
        }

        // Permitir solo números y la tecla de borrar (Backspace)
        if (!Character.isDigit(validar) && validar != KeyEvent.VK_BACK_SPACE) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "INGRESE SOLO NÚMEROS");
        }
    }//GEN-LAST:event_txtnumreferenciaKeyTyped
    public static String capitalizeFirstLetter(String text) {
        if (text == null || text.isEmpty()) {
        return text;
    }
        return text.substring(0, 1).toUpperCase() + text.substring(1).toLowerCase();
    }
    //VALIDACION DE NUMERO DE TELEFONO
    private void verificarDocumento() {
    if (txtnumreferencia.getText().length() < 8) {
        JOptionPane.showMessageDialog(this, "DEBE INGRESAR EXACTAMENTE 8 NÚMEROS");
        txtdocumento.requestFocus();
    } else {
        JOptionPane.showMessageDialog(this, "Número válido");
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonagregar;
    public javax.swing.JButton botoncancelar;
    public javax.swing.JButton botoneliminar;
    public javax.swing.JButton botonlistar;
    public javax.swing.JButton botonmodificar;
    public javax.swing.JButton botonnuevo;
    public javax.swing.JButton botonreporte;
    public javax.swing.JComboBox<String> boxactivo;
    public javax.swing.JComboBox<String> boxdones;
    public javax.swing.JComboBox<String> boxestado;
    public javax.swing.JComboBox<String> boxtalentos;
    public javax.swing.JButton btnbuscar1;
    public com.toedter.calendar.JDateChooser datebautizo;
    public com.toedter.calendar.JDateChooser datenacimiento;
    public com.toedter.calendar.JDateChooser datevonversion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablademiembros;
    public javax.swing.JTextField txtbuscar;
    public javax.swing.JTextField txtdireccion;
    public javax.swing.JTextField txtdocumento;
    public javax.swing.JTextField txtmaterno;
    public javax.swing.JTextField txtnombre;
    public javax.swing.JTextField txtnomfererencia;
    public javax.swing.JTextField txtnumreferencia;
    public javax.swing.JTextField txtpaterno;
    // End of variables declaration//GEN-END:variables

    public String datenacimiento(Date date) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public JDateChooser datevonversion(Date date) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
