/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author LENOVO
 */
public class VistaMinJuve extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaUCE
     */
    public VistaMinJuve() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrUce = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setClosable(true);

        scrUce.setEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("  Ministerio Juvenil Maranatha, comenzo el año 2003, con el objetivo de ayudar a los jovenes de la iglesia.\n\n             Es un ministerio de ayuda que tiene como misión formar y capacitar al joven, para descubrir \n       y desarrollar su llamado de servir a Dios, a partir de las características apostólicas de ser fuertes,\n    permanentes y vencedores para funcionar en la sociedad para transformar su entorno con la cultura \n                                                                              del Reino de Dios.\n\n                                                                       OBJETIVOS PRINCIPALES\n\n   - Formar y capacitar: debemos chequear cuales son las áreas en que nuestros jóvenes tienen \n     carencia formativa sea por el hogar y el sistema educativo para capacitarlos.\n   - Impartición: enseñanza sin impartición solo le da a un banquete a tu mente pero necesariamente  \n     no rompe las cadenas que te oprimen, no es solo enseñar lo correcto es que el factor divino \n     nunca esté ausente de nuestras actividades.\n   - Fuertes, permanentes y vencedores: desarrollar a través de la revelación y la iluminación las \n     tres características de la juventud.\n   - Transformar: que sean ejecutores de un cambios, que nos den a luz una mejor sociedad bajo \n      los principios del reino.\n   - Cultura del reino: que la voluntad de Dios sea la que impregne nuestra nación para tener una \n     sociedad celestial y menos infernal.\n\n                                                                                        HORARIO\n                                                 LAS REUNIONES SON LOS SÁBADOS A HORAS 19:30");
        scrUce.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 0));
        jLabel3.setText("MINISTERIO JUVENIL \"MARANATHA\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrUce, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrUce, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JScrollPane scrUce;
    // End of variables declaration//GEN-END:variables
}
