/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author LENOVO
 */
public class VistaOANSA extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaUCE
     */
    public VistaOANSA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrUce = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setClosable(true);

        scrUce.setEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\t                       Tambien la Niñez y Juventud le Importan a Dios.\n\n                                                                         ¿Qué es OANSA?\n Es un Ministerio dirigido a la niñez y la juventud nivelado gradualmente según las edades y caracterizado \n   por su enseñanza eminentemente Bíblica. OANSA provee Clubes que son operados por las iglesias \n                                   locales que han firmado el Acuerdo Ministerial de OANSA.\n\n\t\t               La Palabra OANSA\n\t                         Obreros Aprobados No Se Avergüenzan\n\n                            “Procura con diligencia presentarte a Dios aprobado como obrero \n                              que no tiene de que avergonzarse que usa bien la palabra de \n                                                                verdad” 2ª a Timoteo 2:15\n\n      \t\t                    Objetivos\n            <> La Salvación  de  los niños  y los jóvenes por medio del Evangelio de Cristo,\n                  llevándolos de la comunidad a los Clubes OANSA y al mismo tiempo alcanzar \n                  también a sus padres, llevando así la familia a la iglesia.\n            <> Retar a través del entrenamiento a niños, niñas, jóvenes y líderes para servir al Señor.\n \n                                                 En otras palabras: Evangelismo y Discipulado\n\n                                                                       Base Fundamental:\n            <> El mensaje del evangelio de la gracia (2ª a los Corintios 5:19 y Efesios 2:8-9).\n            <> La seguridad eterna de nuestra salvación en Jesucristo (Juan 10:27-29 y Filipenses 1:6).\n\n \n                                    - Caminante. Tema general: Jesucristo en el presente.\n                                    - Escalador. Tema general: Jesucristo en el futuro.\n\n");
        scrUce.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 0));
        jLabel3.setText("OBREROS APROBADOS NO SE AVERGUENZAN \"OANSA\" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrUce, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrUce, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JScrollPane scrUce;
    // End of variables declaration//GEN-END:variables
}
